import Vue from 'vue'
import {Popconfirm,Radio ,Modal, Tag,Table, Button, Input, FormModel, Card, Icon, Tooltip, Avatar, DatePicker, Upload, Calendar, Tabs, Empty, Select, Drawer, Steps } from 'ant-design-vue'
Vue.use(FormModel)
Vue.use(Button)
Vue.use(Input)
Vue.use(Card)
Vue.use(Icon)
Vue.use(Tooltip)
Vue.use(Avatar)
Vue.use(DatePicker)
Vue.use(Upload)
Vue.use(Calendar)
Vue.use(Tabs)
Vue.use(Empty)
Vue.use(Select)
Vue.use(Drawer)
Vue.use(Steps)
Vue.use(Table)
Vue.use(Tag)
Vue.use(Modal)
Vue.use(Radio)
Vue.use(Popconfirm)